title: Turbo
url: https://turbo.hotwire.dev
discourse_url: https://discuss.hotwire.dev
github_url: https://github.com/hotwired/turbo
description: The speed of a single-page web application without having to write any JavaScript.

theme: false

defaults:
  - scope:
      path: "*/handbook/*"
    values:
      section: handbook
      section_title: Handbook
      layout_type: docs
      layout: docs
  - scope:
      path: "*/reference/*"
    values:
      section: reference
      section_title: Reference
      layout_type: docs
      layout: docs

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

exclude:
  - node_modules
  - bin
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
