[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_site/"
  # Default build command.
  command = "bundle exec jekyll build"

# fail the build if there are any broken links
[[plugins]]
  package = "netlify-plugin-checklinks"
    [plugins.inputs]
    entryPoints = [
      "*.html",
    ]
    recursive = true
    pretty = true
    skipPatterns = []
    todoPatterns = []
    checkExternal = false
    followSourceMaps = false
